-- 2025-11-27 first release

dofile("/macros/common.lua")
--simulator.setDateTime({year=2024, month=6, day=24, hour=20, min=0, sec=0, lock=true})

simulator.loadModel("signature edge.bin")

simulator.pressKey(KEY_ENTER) -- ack alert
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("/screenshots/screenshot1.png")
simulator.turnRotaryEncoder(14)
simulator.turnRotaryEncoder(-3)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("/screenshots/screenshot2.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("/screenshots/screenshot3.png")
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(2)
simulator.screenshot("/screenshots/screenshot4.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.screenshot("/screenshots/screenshot5.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("/screenshots/screenshot6.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.screenshot("/screenshots/screenshot7.png")
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN, 0.6)