-- 2025-10-04 create
--
-- high level macro for X20S model-lua page
--
-- do a full reload with reset=all
-- load the X20S radio backup
-- load the scripts that enable the Lua icon
-- then load X20S low level macros
-- then load X20S_model-lua 
--
dofile("/macros//model-lua.lua") -- lua is in special radio backup