dofile("common.lua")

simulator.loadModel("geronimo.bin")

simulator.adcValue(ANALOG_STICK_THROTTLE, -80)
--simulator.adcValue(ANALOG_LAST_SLIDER, (-0.0 * 100 / 1024))
simulator.adcValue(ANALOG_LAST_SLIDER, -1024)
simulator.adcValue(ANALOG_STICK_ELEVATOR, -10)
simulator.adcValue(ANALOG_STICK_RUDDER, 20)
simulator.adcValue(ANALOG_STICK_AILERON, 40)

simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_DISP)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/display-widget-bitmap-config.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -80)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-bitmap-type.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -70)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/display-widget-types.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -60)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/display-widget-value-config.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -50)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER, 1)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-value-min.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -40)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/display-widget-value-min-rssi.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -30)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-timer-logs-config.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -20)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-gps-map-config.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -10)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/display-widget-lipo-config.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -90)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-channels-config.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -80)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-2)
simulator.screenshot("../assets/display-widget-line-chart-config.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -70)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-text-config.png")
simulator.adcValue(ANALOG_STICK_THROTTLE, -60)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(7)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-screen-config-options.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

-- now the working widgets
simulator.sleep(10) -- wait 
simulator.adcValue(ANALOG_STICK_THROTTLE, -50)
simulator.sleep(10) -- wait 
simulator.adcValue(ANALOG_STICK_THROTTLE, -40)
simulator.sleep(10) -- wait 
simulator.adcValue(ANALOG_STICK_THROTTLE, -30)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-value-telemetry.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-timer-log.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-timer-log-menu.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-lipo.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-channels.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-line-chart.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-line-chart-options.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-text.png")
-- create new model for default home screen
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(15)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.touch(742, 454)
--simulator.touch(743, 453)
simulator.sleep(2) -- wait 
simulator.screenshot("../assets/display-main-view.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-config-options.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)



simulator.pressKey(KEY_PAGE)
