dofile("common.lua")

-- model must have no curves 
-- then loads zCurves.bin with curves
simulator.loadModel("zBlank.bin")

simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(13)
simulator.screenshot("../assets/model-icon-curves.png")
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-add.png")
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-edit.png")
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-type.png")
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-fn-types.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-fn-xgt0.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(389, 449)
simulator.touch(389, 449)
simulator.turnRotaryEncoder(2)
simulator.screenshot("../assets/model-curves-fn-xgt0-offset.png")
simulator.turnRotaryEncoder(-2)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-fn-xlt0.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-fn-barx.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-fn-fgt0.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-fn-flt0.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-fn-barf.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1) -- back to type
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- 
simulator.pressKey(KEY_ENTER) -- select custom
-- simulator.screenshot("../assets/model-curves-custom5.png")
-- attach curve to a mix so that Input option appears
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN) -- back to models
simulator.turnRotaryEncoder(-9)
simulator.pressKey(KEY_ENTER) -- back to mixes
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER) -- to elevator
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- edit
simulator.turnRotaryEncoder(3) -- 
simulator.pressKey(KEY_ENTER) -- select curve
-- simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2) -- select curve1
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN) --back to models
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER) -- go to curves
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
-- simulator.screenshot("./screenshot1.png")
simulator.turnRotaryEncoder(5)
simulator.screenshot("../assets/model-curves-custom5.png")

simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_ENTER) -- open points edit
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- edit -100 point
simulator.touch(389, 445) -- 1%
simulator.touch(386, 445) --10%
simulator.turnRotaryEncoder(-10)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(391, 449)
simulator.touch(391, 449)
simulator.turnRotaryEncoder(-2)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(394, 447)
simulator.touch(394, 447)
simulator.turnRotaryEncoder(1)
simulator.touch(36, 447)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(391, 450)
simulator.touch(391, 448)
simulator.turnRotaryEncoder(2)
simulator.touch(28, 447)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(389, 443)
simulator.touch(389, 443)
simulator.turnRotaryEncoder(1)
simulator.touch(34, 444)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-curves-custom5-2.png")
simulator.turnRotaryEncoder(-7)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-curves-custom5-2-smooth.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN) --
simulator.pressKey(KEY_RTN) -- retun to models
simulator.turnRotaryEncoder(1) -- to vars
simulator.screenshot("../assets/model-icon-vars.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-vars-add.png")
simulator.turnRotaryEncoder(1) -- to vars
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-vars-edit.png")
simulator.pressKey(KEY_RTN, 1)


simulator.loadModel("zCurves.bin")


simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(13)
simulator.pressKey(KEY_ENTER) -- curves
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- select cv1
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- edit cv1
simulator.screenshot("../assets/model-curves-expo.png")
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- cv2
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- edit cv2
simulator.turnRotaryEncoder(10)
simulator.pressKey(KEY_ENTER) -- edit points
simulator.turnRotaryEncoder(5)
simulator.turnRotaryEncoder(-2)
simulator.screenshot("../assets/model-curves-custom-easy-off.png")
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.turnRotaryEncoder(3)
simulator.screenshot("./screenshot3.png") -- wait for bug fix cannot scroll
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- cv3
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- edit cv3
simulator.turnRotaryEncoder(4)
simulator.screenshot("../assets/model-curves-fn-offset-var.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- cv4
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(10)
simulator.pressKey(KEY_ENTER)
-- simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(5)
simulator.turnRotaryEncoder(-2)
simulator.screenshot("../assets/model-curves-custom-with-var.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
