dofile("common.lua")

simulator.loadModel("blaster.bin")

simulator.adcValue(ANALOG_STICK_THROTTLE, -70)
--simulator.adcValue(ANALOG_LAST_SLIDER, (-0.0 * 100 / 1024))
simulator.adcValue(ANALOG_LAST_SLIDER, -1024)
simulator.adcValue(ANALOG_STICK_ELEVATOR, -10)
simulator.sleep(1) -- wait for adc values
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(4)
simulator.screenshot("../assets/model-mixes-chview-elevator.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.screenshot("../assets/model-mixes-chview-select.png")
simulator.pressKey(KEY_ENTER)
simulator.sleep(3) -- wait 
simulator.screenshot("../assets/model-mixes-chview-elevator-channel-view.png")
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/model-mixes-chview-elevator-channel.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-mixes-chview-collapsed.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.screenshot("../assets/model-mixes-chview-table-view-select.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-mixes-chview-back-at-mixes-view.png")
simulator.pressKey(KEY_RTN, 1)

