-- 2025-01-02 create 
-- 0 = STICK_LEFT_HORIZONTAL (Rudder)
-- 1 = STICK_LEFT_VERTICAL (Throttle mode 2)
-- 2 = STICK_RIGHT_VERTICAL (Elevator)
-- 3 = STICK_RIGHT_HORIZONTAL (Aileron)

dofile("common.lua")
--simulator.setDateTime({year=2024, month=6, day=24, hour=20, min=0, sec=0, lock=true})

simulator.loadModel("zblank.bin")
-- load user defined checklist
simulator.sleep(1) -- wait for checklist to load
simulator.pressKey(KEY_ENTER) -- accept checklist
simulator.pressKey(KEY_MDL) 
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- model select
simulator.turnRotaryEncoder(5) -- go to + icon
simulator.pressKey(KEY_ENTER) -- create new model
simulator.turnRotaryEncoder(1) -- highlight create model select
simulator.screenshot("../assets/tut-fw-eg-create-model.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/tut-fw-eg-wiz-create-airplane.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/tut-fw-eg-wiz-rx.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/tut-fw-eg-wiz-engine.png")
simulator.pressKey(KEY_PAGE)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/tut-fw-eg-wiz-ail-flaps.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/tut-fw-eg-wiz-tail.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/tut-fw-eg-wiz-ele-rudd.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/tut-fw-eg-wiz-ch-reassign.png")
simulator.pressKey(KEY_PAGE)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(316, 356)
simulator.touch(123, 299)
simulator.touch(67, 406)
simulator.touch(200, 303)
simulator.touch(240, 403)
simulator.touch(86, 353)
simulator.touch(640, 403)
simulator.touch(757, 303)
simulator.touch(713, 350)
simulator.touch(200, 300)
simulator.touch(738, 449)
simulator.screenshot("../assets/tut-fw-eg-wiz-name.png")
simulator.pressKey(KEY_PAGE)
--end of wizard, start of mixes
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(4)
simulator.screenshot("../assets/tut-fw-eg-mixes-icon.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/tut-fw-eg-mixes.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-edit.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- cursor on ail mix
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-mix.png")
simulator.turnRotaryEncoder(5) -- cursor on weight
--simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(1, 1) -- set switch SB mid as rates switch
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(391, 447)
simulator.turnRotaryEncoder(-4)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(1, 2) -- set switch SB down as rates switch
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(393, 444)
simulator.turnRotaryEncoder(-7)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-weight-rates.png")
simulator.turnRotaryEncoder(-8)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(393, 449)
simulator.turnRotaryEncoder(6)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(1, 1) -- set switch SB mid as rates switch
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(0)
simulator.touch(391, 450)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(1, 2) -- set switch SB down as rates switch
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(394, 453)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_RTN)
--simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-expo-rates.png")
simulator.turnRotaryEncoder(10)
simulator.pressKey(KEY_ENTER) -- diff
simulator.touch(397, 448)
simulator.turnRotaryEncoder(5) -- 50% diff
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-diff-50.png")
simulator.pressKey(KEY_ENTER, 1)
simulator.turnRotaryEncoder(3)
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-diff-use-source.png")
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-diff-use-pot1.png")
simulator.pressKey(KEY_ENTER, 1)
simulator.turnRotaryEncoder(3)
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-diff-convert-to-value.png")
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.touch(396, 449)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/tut-fw-eg-mixes-ail-trim.png")
--simulator.pressKey(KEY_ENTER, 1)
--end of ail mix review, start of ele mix review
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN) 
simulator.turnRotaryEncoder(1) --- cursor on ele
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER) -- edit ele mix
simulator.turnRotaryEncoder(6) -- cursor on weight
--simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(1, 1) -- set switch SB mid as rates switch
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(391, 447)
simulator.turnRotaryEncoder(-4)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(1, 2) -- set switch SB down as rates switch
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(393, 444)
simulator.turnRotaryEncoder(-7)
simulator.pressKey(KEY_RTN)
-- simulator.screenshot("../assets/tut-fw-eg-mixes-ele-weight-rates.png")
simulator.turnRotaryEncoder(-8)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(393, 449)
simulator.turnRotaryEncoder(6)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(1, 1) -- set switch SB mid as rates switch
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(0)
simulator.touch(391, 450)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(1, 2) -- set switch SB down as rates switch
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(394, 453)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_RTN)
--simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/tut-fw-eg-mixes-ele-expo-rates.png")
simulator.pressKey(KEY_RTN, 1)

-- end of ele, start of thr
simulator.setSwitch(0, 2) -- move switch SA down
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- cursor on thr mix
simulator.screenshot("../assets/tut-fw-eg-mixes-thr-edit.png")
simulator.turnRotaryEncoder(4) -- cursor to thr cut
simulator.pressKey(KEY_ENTER) -- open thr cut section
simulator.turnRotaryEncoder(1) -- cursor to active cond
simulator.pressKey(KEY_ENTER)
-- select sw SA down
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
-- end of sw SA select
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(4) -- scroll to see all thr cut
--simulator.screenshot("../assets/tut-fw-eg-mixes-thr-cut.png")
simulator.turnRotaryEncoder(-5) -- scroll back to thr cut heading
simulator.screenshot("../assets/tut-fw-eg-mixes-thr-cut.png")
simulator.turnRotaryEncoder(2) --  scroll to Sticky
simulator.pressKey(KEY_ENTER) -- set Sticky ON
simulator.turnRotaryEncoder(-3) -- move cursor off thr cut to allow sim to execute changes
simulator.sleep(1) -- wait for sim
simulator.turnRotaryEncoder(3) -- scroll back to Sticky
simulator.screenshot("../assets/tut-fw-eg-mixes-thr-cut-sticky-on.png")
simulator.pressKey(KEY_ENTER) -- set Sticky Off
simulator.turnRotaryEncoder(-3) -- scroll to low pos trim
simulator.pressKey(KEY_ENTER) -- set low pos trim On
simulator.screenshot("../assets/tut-fw-eg-mixes-thr-low-pos-trim.png")
simulator.pressKey(KEY_ENTER) -- set low pos trim Off
simulator.turnRotaryEncoder(6) -- scroll down to thr hold
simulator.pressKey(KEY_ENTER) -- open thr hold
-- back to old section
simulator.turnRotaryEncoder(1) -- scroll to active cond
simulator.pressKey(KEY_ENTER) -- edit thr hold sw
-- simulator.setSwitch(2, 2) -- move switch SA -- sim funny
-- simulator.sleep(1) -- wait for sim
-- simulator.setSwitch(0, 2) -- set switch SA down as thr hold switch
-- select sw SA down
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
-- end of sw SA select
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(5)

--simulator.screenshot("./screenshot5.png") -- temp turn around mark
simulator.turnRotaryEncoder(-6)
simulator.screenshot("../assets/tut-fw-eg-mixes-thr-hold.png")
simulator.turnRotaryEncoder(7)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/tut-fw-eg-mixes-thr-ch3.png")
simulator.pressKey(KEY_RTN, 1)

-- end of thr mix, start of flaps
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(4) 
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(5) -- cursor on flaps
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- cursor on edit
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3) -- cusor on input
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/tut-fw-eg-mixes-flaps-input.png")
simulator.turnRotaryEncoder(6)
simulator.pressKey(KEY_ENTER)
simulator.touch(393, 443)
simulator.turnRotaryEncoder(7)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.touch(401, 435)
simulator.turnRotaryEncoder(7)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/tut-fw-eg-mixes-flaps-weights.png")
simulator.pressKey(KEY_RTN, 1)

-- end of flaps mix, start of outputs
simulator.setAnalog(1, -100) -- set thr to -100
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(5)
simulator.screenshot("../assets/tut-fw-eg-outputs-icon.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/tut-fw-eg-outputs.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(6)
simulator.screenshot("../assets/tut-fw-eg-outputs-edit-ail.png")
simulator.pressKey(KEY_RTN, 1)

--end of outputs, start of retracts
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/tut-fw-eg-mixes-library.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.touch(737, 398)
simulator.touch(737, 398)
simulator.touch(737, 398)
simulator.touch(737, 398)
simulator.touch(737, 398)
simulator.touch(737, 398)
simulator.touch(737, 398)
simulator.touch(737, 398)
simulator.touch(277, 302)
simulator.touch(57, 403)
simulator.touch(196, 307)
simulator.touch(366, 303)
simulator.touch(284, 302)
simulator.touch(84, 351)
simulator.touch(316, 405)
simulator.touch(364, 306)
simulator.touch(159, 356)
simulator.touch(749, 447)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/tut-fw-eg-retracts-source.png")
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(8)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/tut-fw-eg-retracts-outputs.png")
simulator.pressKey(KEY_RTN, 1)

