--2024-12-04 change adcValue() to setAnalog()
-- 2025-07-22 adapt macro to new Ethos 1.7 source select
-- 2025-08-09 add comments
-- 2025-08-15 enable dofile again
-- 2025-09-09 add bottombar-glider.png
-- 2026-04-14 adapt to new config styles
-- 2026-04-15 adapt to new config styles new sshots

-- 0 = STICK_LEFT_HORIZONTAL (Rudder)
-- 1 = STICK_LEFT_VERTICAL (Throttle mode 2)
-- 2 = STICK_RIGHT_VERTICAL (Elevator)
-- 3 = STICK_RIGHT_HORIZONTAL (Aileron)

-- The timer logs are generated by having timer 1 always counting up, and then being reset at odd intervals by two logic switches which trigger an sf which resets the timer.


dofile("common.lua")
-- simulator.setDateTime({year=2024, month=6, day=24, hour=20, min=0, sec=0, lock=true})

-- use a blank model for the initial screenshots
simulator.loadModel("zblank.bin")
-- load user defined checklist
simulator.sleep(1) -- wait for checklist to load
--simulator.screenshot("/screenshots/model-checklist-user-checklist.png")
simulator.pressKey(KEY_ENTER) --ack alert

-- open configure sreens
simulator.pressKey(KEY_DISP) -- open configure sreens
-- simulator.screenshot("/screenshots/display-home.png")
--simulator.turnRotaryEncoder(2)
--simulator.pressKey(KEY_ENTER)
--simulator.screenshot("/screenshots/display-change-source.png")
--simulator.pressKey(KEY_RTN)
--simulator.turnRotaryEncoder(8) --scroll to new screen
simulator.screenshot("/screenshots/display-home.png")
simulator.turnRotaryEncoder(1) --scroll to configure of first widget
--simulator.pressKey(KEY_ENTER) --y
simulator.screenshot("/screenshots/display-widget-bitmap-config-selected.png")
simulator.pressKey(KEY_RTN) -- deselect
simulator.pressKey(KEY_PAGE) -- go to '+' button
simulator.pressKey(KEY_ENTER) -- add screen
simulator.turnRotaryEncoder(4) --scroll to 9 panel
simulator.pressKey(KEY_ENTER) -- select
simulator.screenshot("/screenshots/display-home-screen2.png")
simulator.pressKey(KEY_RTN, 1)


simulator.loadModel("geronimo.bin")

simulator.setAnalog(throttleAnalogIndex, 80)
--simulator.setAnalog(ANALOG_LAST_SLIDER, (-0.0 * 100 / 1024))
simulator.setAnalog(ANALOG_LAST_SLIDER, -100)
simulator.setAnalog(elevatorAnalogIndex, -10)
simulator.setAnalog(0, 20)
simulator.setAnalog(3, 40)

simulator.pressKey(KEY_ENTER) --clear warning
simulator.pressKey(KEY_DISP) --go to configure screens



simulator.turnRotaryEncoder(1) --scroll to configure of first widget
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(1) --scroll to widget select(bitmap is default)
simulator.screenshot("/screenshots/display-widget-bitmap-config.png")
simulator.setAnalog(throttleAnalogIndex, 80) -- start setting points for line chart demo
simulator.turnRotaryEncoder(1) --scroll to bitmap type
simulator.pressKey(KEY_ENTER) --y
simulator.screenshot("/screenshots/display-widget-bitmap-type.png")
simulator.setAnalog(throttleAnalogIndex, 70)
simulator.pressKey(KEY_RTN) --deselectbtype
simulator.turnRotaryEncoder(-1) --scroll back to widget select
simulator.pressKey(KEY_ENTER) -- open widgets list
simulator.turnRotaryEncoder(-1) --scroll back to '---'
simulator.screenshot("/screenshots/display-widget-types.png")
simulator.setAnalog(throttleAnalogIndex, 60)
simulator.turnRotaryEncoder(2) --scroll to value widget
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(1) --scroll to source select
simulator.pressKey(KEY_ENTER) --open
--[[
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN) --rssi def
]]--
--simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(10) --scroll to telem
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(0) --scroll to RSSI
simulator.pressKey(KEY_ENTER) --y
--
simulator.turnRotaryEncoder(-1) --scroll back 
simulator.screenshot("/screenshots/display-widget-value-config.png")
simulator.setAnalog(throttleAnalogIndex, 50)
simulator.turnRotaryEncoder(1) --scroll back to source
simulator.pressKey(KEY_ENTER, 1) --long ENT
simulator.turnRotaryEncoder(1) --scroll to min
simulator.pressKey(KEY_ENTER) --y
simulator.screenshot("/screenshots/display-widget-value-min.png")
simulator.setAnalog(throttleAnalogIndex, 40)
simulator.pressKey(KEY_RTN) --return
simulator.turnRotaryEncoder(-1) --scroll back to w type
simulator.screenshot("/screenshots/display-widget-value-min-rssi.png")
simulator.setAnalog(throttleAnalogIndex, 30)
simulator.pressKey(KEY_ENTER) --open w type
simulator.turnRotaryEncoder(1) --scroll to timer logs
simulator.pressKey(KEY_ENTER) --y
simulator.screenshot("/screenshots/display-widget-timer-logs-config.png")
simulator.setAnalog(throttleAnalogIndex, 20)
simulator.pressKey(KEY_ENTER) -- enter cancels
simulator.turnRotaryEncoder(1) --scroll to gps
simulator.pressKey(KEY_ENTER) --y
simulator.screenshot("/screenshots/display-widget-gps-map-config.png")
simulator.setAnalog(throttleAnalogIndex, 10)
simulator.pressKey(KEY_ENTER) --enter cancels
simulator.turnRotaryEncoder(1) --scroll to lipo
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(1) --scroll to sensor select
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(1) --scroll to lipo
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(-1) --scroll back to w type
simulator.screenshot("/screenshots/display-widget-lipo-config.png")
simulator.setAnalog(throttleAnalogIndex, 90)
simulator.pressKey(KEY_ENTER) --open w select
simulator.turnRotaryEncoder(1) --scroll to channels
simulator.pressKey(KEY_ENTER) --y
simulator.screenshot("/screenshots/display-widget-channels-config.png")
simulator.setAnalog(throttleAnalogIndex, 80)
simulator.pressKey(KEY_ENTER) --ent cancels
simulator.turnRotaryEncoder(1) --scroll to line chart
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(1) --scroll to source select
simulator.pressKey(KEY_ENTER) --y
--[[select rssi
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
]]--
simulator.turnRotaryEncoder(10) --scroll to telem
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(0) --scroll to RSSI
simulator.screenshot("/screenshots/display-change-source.png")
simulator.pressKey(KEY_ENTER) --y
--
simulator.turnRotaryEncoder(1) --scroll to pause cond
simulator.pressKey(KEY_ENTER) --y
--[[select sa down
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
]]--
simulator.turnRotaryEncoder(3) --scroll to sw's
simulator.pressKey(KEY_ENTER) --y
simulator.turnRotaryEncoder(2) --sw SA down
simulator.pressKey(KEY_ENTER) --y
--
simulator.turnRotaryEncoder(-2) --scroll back to w select
simulator.screenshot("/screenshots/display-widget-line-chart-config.png")
simulator.setAnalog(throttleAnalogIndex, 70)
simulator.pressKey(KEY_ENTER) --open w select
simulator.turnRotaryEncoder(1) --scroll to text w
simulator.pressKey(KEY_ENTER) --y
simulator.screenshot("/screenshots/display-widget-text-config.png")
simulator.setAnalog(throttleAnalogIndex, 60)
simulator.pressKey(KEY_RTN) --return from w
simulator.pressKey(KEY_RTN)

--simulator.turnRotaryEncoder(7) --scroll to screen 2
simulator.pressKey(KEY_PAGE) -- page to screen 2
--simulator.pressKey(KEY_ENTER) --open
simulator.pressKey(KEY_ENTER, 0.6) --open config options 
simulator.screenshot("/screenshots/display-screen-config-options.png")
simulator.pressKey(KEY_RTN) -- exit options
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

-- now the working widgets
simulator.sleep(10) -- wait 
simulator.setAnalog(throttleAnalogIndex, 50) --set more points for line chart demo
simulator.sleep(10) -- wait 
simulator.setAnalog(throttleAnalogIndex, 40)
simulator.sleep(10) -- wait 
simulator.setAnalog(throttleAnalogIndex, 30)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("/screenshots/display-widget-value-telemetry.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("/screenshots/display-widget-timer-log.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("/screenshots/display-widget-timer-log-menu.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("/screenshots/display-widget-lipo.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("/screenshots/display-widget-channels.png")
simulator.screenshot("/screenshots/bottombar-glider.png", {x=0, y=410, w=800, h=70})
simulator.pressKey(KEY_PAGE)
simulator.screenshot("/screenshots/display-widget-line-chart.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("/screenshots/display-widget-line-chart-options.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("/screenshots/display-widget-text.png")
-- create new model for default home screen
simulator.pressKey(KEY_MDL) -- open model menu
simulator.turnRotaryEncoder(1) -- scroll to model select
simulator.pressKey(KEY_ENTER) -- open
simulator.turnRotaryEncoder(18) -- scroll to plus button at the end
simulator.pressKey(KEY_ENTER) -- create new model
simulator.turnRotaryEncoder(1) -- scroll to airplane
simulator.pressKey(KEY_ENTER) -- select
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.touch(742, 454)
--simulator.touch(743, 453)
simulator.sleep(2) -- wait 
simulator.screenshot("/screenshots/display-main-view.png")
simulator.turnRotaryEncoder(1) -- scroll to configure
simulator.pressKey(KEY_ENTER) -- open 
simulator.screenshot("/screenshots/display-widget-config-options.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN, 1)
