-- 2025-01-03 first release

dofile("common.lua")
--simulator.setDateTime({year=2024, month=6, day=24, hour=20, min=0, sec=0, lock=true})

simulator.loadModel("katana.bin")

simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_MDL)
simulator.pressKey(KEY_PAGE) -- 2nd page
simulator.turnRotaryEncoder(1) -- highlight telemetry
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(13)
simulator.screenshot("../assets/how-to-low-batt-telemetry-lipo-sensor.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

--simulator.pressKey(KEY_ENTER)
--simulator.pressKey(KEY_MDL)
--simulator.pressKey(KEY_PAGE)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(470, 395)
simulator.touch(67, 403)
simulator.touch(78, 357)
simulator.touch(367, 307)
simulator.touch(366, 305)
simulator.touch(66, 400)
simulator.touch(712, 352)
simulator.touch(67, 401)
simulator.touch(685, 298)
simulator.touch(116, 299)
simulator.touch(732, 450)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(8)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(6)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/how-to-low-batt-lsw-battlow-lipo.png")
simulator.pressKey(KEY_ENTER, 1)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/how-to-low-batt-lsw-battlow-lipo-select-lowest.png")
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(395, 447)
simulator.turnRotaryEncoder(4)
simulator.touch(388, 450)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_RTN)
--simulator.screenshot("../assets/how-to-low-batt-lsw-battlow-lipo-lowest.png")
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER) -- edit delay before active
simulator.touch(391, 447)
simulator.turnRotaryEncoder(4)

simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/how-to-low-batt-lsw-battlow-lipo-lowest.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/how-to-low-batt-lsw-summary.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/how-to-low-batt-sf-battlow.png")
--simulator.turnRotaryEncoder(5)
simulator.turnRotaryEncoder(2)

simulator.pressKey(KEY_ENTER)
simulator.touch(392, 446)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)

simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(6)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/how-to-low-batt-sf-play-value-lipo.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/how-to-low-batt-sf-play-value-lipo-summary.png")
simulator.pressKey(KEY_RTN, 1)
