
dofile("common.lua")

simulator.loadModel("rarebear.bin")

simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(11)
simulator.screenshot("../assets/model-icon-lsw.png")
simulator.pressKey(KEY_ENTER)

simulator.setSwitch(0, 1)
simulator.sleep(1) -- wait for checklist to load
simulator.screenshot("../assets/model-lsw-confirm-lsw-true.png")
simulator.pressKey(KEY_ENTER)
simulator.setSwitch(0, 0)
simulator.sleep(1) -- wait for checklist to load
simulator.screenshot("../assets/model-lsw-confirm-lsw-false.png")
simulator.pressKey(KEY_ENTER)

simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-menu.png")
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-move.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.screenshot("../assets/model-lsw-A~X.png")

simulator.turnRotaryEncoder(11)
-- simulator.screenshot("./screenshot1.png")
simulator.turnRotaryEncoder(-7)
simulator.screenshot("../assets/model-lsw-common-parameters.png")
simulator.turnRotaryEncoder(-5)
simulator.turnRotaryEncoder(2)

simulator.pressKey(KEY_ENTER) -- delta X
simulator.turnRotaryEncoder(6)
simulator.pressKey(KEY_ENTER) 
simulator.turnRotaryEncoder(-2)
simulator.pressKey(KEY_ENTER)
simulator.touch(64, 399)
simulator.touch(241, 351)
simulator.touch(203, 305)
simulator.touch(717, 354)
simulator.touch(357, 302)
simulator.touch(76, 352)
simulator.touch(64, 445)
simulator.touch(124, 302)
simulator.touch(757, 304)
simulator.touch(757, 304)
simulator.touch(57, 450)
simulator.touch(641, 399)
simulator.touch(53, 403)
simulator.touch(77, 354)
simulator.touch(58, 399)
simulator.touch(475, 358)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(33)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(392, 449)
simulator.touch(392, 449)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-lsw-delta-gtX.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(8)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-range.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-AND.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-OR.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-XOR.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-timer-generator.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-sticky.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-edge.png")
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
-- simulator.pressKey(KEY_ENTER)
-- simulator.pressKey(KEY_ENTER, 1)
-- simulator.pressKey(KEY_ENTER)
-- simulator.turnRotaryEncoder(0)
-- simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-lsw-edge-rising-edge.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.touch(388, 446)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/model-lsw-edge-during-gt0-rising-edge.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.touch(390, 439)
simulator.touch(40, 443)
simulator.turnRotaryEncoder(-2)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-lsw-edge-during-eq0.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(30)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-lsw-edge-during-gt0.png")

simulator.turnRotaryEncoder(-3)

simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-8)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(8)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER, 1)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.touch(638, 266)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-lsw-delta-AgtX.png")
simulator.turnRotaryEncoder(-2)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(164, 352)
simulator.touch(63, 396)
simulator.touch(357, 310)
simulator.touch(598, 298)
simulator.touch(319, 399)
simulator.touch(637, 355)
simulator.touch(60, 399)
simulator.touch(243, 355)
simulator.touch(65, 402)
simulator.touch(200, 306)
simulator.touch(360, 305)
simulator.touch(199, 305)
simulator.touch(321, 398)
simulator.touch(361, 304)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.touch(387, 439)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER, 1)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-lsw-ignore-trainer-input.png")

simulator.pressKey(KEY_RTN, 1)
