dofile("common.lua")
--simulator.setDateTime({year=2024, month=6, day=24, hour=20, min=0, sec=0, lock=true})

simulator.loadModel("rarebear.bin")

simulator.touch(661, 194)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_MDL)
simulator.pressKey(KEY_PAGE)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/model-icon-telemetry.png")
--[[]]
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-discover-new-sensors-off-1.png")
simulator.turnRotaryEncoder(1) -- scroll to discover param
simulator.screenshot("../assets/model-telemetry-discover-new-sensors-off.png")
--
-- get blank start after deleting all sensors
simulator.turnRotaryEncoder(1) -- scroll to delete all sensors
simulator.pressKey(KEY_ENTER) -- delete all sensors
simulator.pressKey(KEY_ENTER) -- confirm delete all sensors
simulator.sleep(1) -- wait 
simulator.screenshot("../assets/model-telemetry-sensors-deleted.png")
--
simulator.turnRotaryEncoder(-1) -- scroll back to discover sensors
--
-- simulator.turnRotaryEncoder(1) -- scroll to discover sensors
simulator.pressKey(KEY_ENTER) -- discover new sensors
simulator.sleep(10) -- wait 
simulator.screenshot("../assets/model-telemetry-discover-new-sensors-on.png")
simulator.pressKey(KEY_ENTER) -- turn discover off again
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-comp-only-confirm.png")
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-rssi-individual-alert.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
--simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.sleep(2) -- wait 
simulator.screenshot("../assets/model-telemetry-bt-option.png")
simulator.sleep(1) -- wait 
simulator.pressKey(KEY_ENTER) -- turn off BT

--simulator.turnRotaryEncoder(7)
simulator.turnRotaryEncoder(4) -- scroll to sensor list
simulator.screenshot("../assets/model-telemetry-discovered-new-sensors.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- scroll to rssi
simulator.screenshot("../assets/model-telemetry-edit-option-select.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-edit-rssi-sensor.png")
simulator.turnRotaryEncoder(16)
simulator.screenshot("../assets/model-telemetry-edit-rssi-sensor-2.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(5) -- scroll to vfr
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-edit-vfr-sensor.png")
simulator.turnRotaryEncoder(18)
simulator.screenshot("../assets/model-telemetry-edit-vfr-sensor-2.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(14)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/model-telemetry-edit-adc2-sensor-select.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-edit-adc2-sensor.png")
simulator.turnRotaryEncoder(13)
simulator.screenshot("../assets/model-telemetry-edit-adc2-sensor-2.png")
-- simulator.screenshot("./screenshot3.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-8)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-edit-vspeed-sensor.png")
simulator.turnRotaryEncoder(10)
simulator.screenshot("../assets/model-telemetry-edit-vspeed-sensor-2.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

-- do diy sensor
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(6)
simulator.screenshot("../assets/model-telemetry-diy-sensor-select.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-diy-sensor-edit.png")
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.sleep(1) -- wait 
simulator.screenshot("../assets/model-telemetry-diy-sensor-auto-detect.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

-- now do calculated sensors
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(7)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-select.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-consumption.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-consumption-select.png")

simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-distance.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(7)
-- simulator.screenshot("../assets/model-telemetry-calculated-sensor-select.png")
simulator.pressKey(KEY_ENTER)
-- simulator.screenshot("../assets/model-telemetry-calculated-sensor-consumption.png")
simulator.turnRotaryEncoder(1) --scroll to fn
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2) --scroll to trip
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-trip.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(7)
-- simulator.screenshot("../assets/model-telemetry-calculated-sensor-select.png")
simulator.pressKey(KEY_ENTER)
-- simulator.screenshot("../assets/model-telemetry-calculated-sensor-consumption.png")
simulator.turnRotaryEncoder(1) --scroll to fn
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3) --scroll to multi lipo
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-multi-lipo.png")
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-multi-lipo-2.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(7)
-- simulator.screenshot("../assets/model-telemetry-calculated-sensor-select.png")
simulator.pressKey(KEY_ENTER)
-- simulator.screenshot("../assets/model-telemetry-calculated-sensor-consumption.png")
simulator.turnRotaryEncoder(1) --scroll to fn
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-percent.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(7)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-power.png")
simulator.turnRotaryEncoder(8)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-calculated-sensor-power-2.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

-- do calculated custom power sensor
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(7) -- scroll to calculated sensor
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- scroll to formula
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(6) -- scroll to custom
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor.png")
-- simulator.turnRotaryEncoder(9) -- scroll to add
-- simulator.screenshot("./screenshot36.png")
-- simulator.pressKey(KEY_ENTER)
-- simulator.turnRotaryEncoder(-8)
simulator.turnRotaryEncoder(1) -- scroll to name
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.touch(732, 402)
simulator.touch(732, 402)
simulator.touch(732, 402)
simulator.touch(732, 402)
simulator.touch(732, 402)
simulator.touch(732, 402)
simulator.touch(732, 402)
simulator.touch(732, 402)
simulator.touch(731, 403)
simulator.touch(731, 403)
simulator.touch(731, 403)
simulator.touch(731, 403)
simulator.touch(731, 403)
simulator.touch(640, 399)
simulator.touch(73, 393)
simulator.touch(79, 351)
simulator.touch(242, 401)
simulator.touch(57, 394)
simulator.touch(751, 305)
simulator.touch(72, 394)
simulator.touch(687, 308)
simulator.touch(117, 301)
simulator.touch(199, 302)
simulator.touch(285, 305)
simulator.touch(735, 454)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-maxpower.png")
simulator.turnRotaryEncoder(7) -- scroll to source
-- take screenshots for intro
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-add-action.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-add-action-select.png")
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1) -- scroll back to delete actions
simulator.pressKey(KEY_ENTER) -- delete
simulator.pressKey(KEY_ENTER) -- confirm

simulator.pressKey(KEY_ENTER) -- edit source
simulator.turnRotaryEncoder(1) -- cat
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(10) -- scroll to telem
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2) -- scroll to member
simulator.pressKey(KEY_ENTER)
-- simulator.turnRotaryEncoder(21)
simulator.turnRotaryEncoder(21) -- scroll to VFAS
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
-- simulator.turnRotaryEncoder(2)
simulator.turnRotaryEncoder(1) -- scroll to add
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- scroll to fn
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2) -- scroll to multiply
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- scroll to surce
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- scroll to cat
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(10) -- scroll to telem
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2) -- scroll to member
simulator.pressKey(KEY_ENTER)
-- simulator.turnRotaryEncoder(13) -- 
simulator.turnRotaryEncoder(13) -- scroll to current
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1) -- scroll to add
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- scroll to fn
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(5) -- scroll to max
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- select cat
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1) -- cat
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(10) -- scroll to telem
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2) -- scroll to memebr
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1) -- reverse scroll to MaxPower
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-maxpower-2.png")
--simulator.turnRotaryEncoder(-14)
--simulator.screenshot("./screenshot38.png")
--simulator.pressKey(KEY_RTN, 1)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

-- do subtract example
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(7)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(6)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.pressKey(KEY_DISP)
simulator.touch(739, 401)
simulator.touch(739, 401)
simulator.touch(739, 401)
simulator.touch(739, 401)
simulator.touch(739, 401)
simulator.touch(739, 401)
simulator.touch(739, 401)
simulator.touch(739, 401)
simulator.touch(739, 401)
simulator.touch(738, 401)
simulator.touch(738, 401)
simulator.touch(738, 401)
simulator.touch(166, 348)
simulator.touch(72, 408)
simulator.touch(517, 303)
simulator.touch(480, 401)
simulator.touch(364, 300)
simulator.touch(285, 301)
simulator.touch(59, 396)
simulator.touch(200, 303)
simulator.touch(63, 398)
simulator.touch(242, 409)
simulator.touch(83, 354)
simulator.touch(633, 404)
simulator.touch(754, 305)
simulator.touch(726, 350)
simulator.touch(203, 304)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-subtrexample.png")
simulator.turnRotaryEncoder(7) -- scroll to source
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(10) -- scroll to custom
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-subtrexample-subtract.png")
simulator.turnRotaryEncoder(1)
-- simulator.pressKey(KEY_ENTER)
-- simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_ENTER, 1) -- long press line source
simulator.turnRotaryEncoder(3)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-subtrexample-conv2val.png")
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.touch(391, 451)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-subtr-20.png")
--simulator.screenshot("./screenshot7.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
--simulator.pressKey(KEY_RTN)
--
simulator.setAnalog(1, 100) -- set thr to -100
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(7)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(6)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(8)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-internal-value-max.png")
simulator.setAnalog(1, -100) -- set thr to -100
simulator.sleep(0.6) -- wait 
simulator.screenshot("../assets/model-telemetry-edit-custom-sensor-internal-value-min.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
