--2024-12-04 change adcValue() to setAnalog()
-- 0 = STICK_LEFT_HORIZONTAL (Rudder)
-- 1 = STICK_LEFT_VERTICAL (Throttle mode 2)
-- 2 = STICK_RIGHT_VERTICAL (Elevator)
-- 3 = STICK_RIGHT_HORIZONTAL (Aileron)

dofile("common.lua")
--simulator.setDateTime({year=2024, month=6, day=24, hour=20, min=0, sec=0, lock=true})

simulator.loadModel("geronimo.bin")

simulator.setAnalog(1, 80)
--simulator.setAnalog(ANALOG_LAST_SLIDER, (-0.0 * 100 / 1024))
simulator.setAnalog(ANALOG_LAST_SLIDER, -100)
simulator.setAnalog(2, -10)
simulator.setAnalog(0, 20)
simulator.setAnalog(3, 40)

simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_DISP)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/display-widget-bitmap-config.png")
simulator.setAnalog(1, 80)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-bitmap-type.png")
simulator.setAnalog(1, 70)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/display-widget-types.png")
simulator.setAnalog(1, 60)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/display-widget-value-config.png")
simulator.setAnalog(1, 50)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER, 1)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-value-min.png")
simulator.setAnalog(1, 40)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/display-widget-value-min-rssi.png")
simulator.setAnalog(1, 30)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-timer-logs-config.png")
simulator.setAnalog(1, 20)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-gps-map-config.png")
simulator.setAnalog(1, 10)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(-1)
simulator.screenshot("../assets/display-widget-lipo-config.png")
simulator.setAnalog(1, 90)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-channels-config.png")
simulator.setAnalog(1, 80)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(9)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(-2)
simulator.screenshot("../assets/display-widget-line-chart-config.png")
simulator.setAnalog(1, 70)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-text-config.png")
simulator.setAnalog(1, 60)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(7)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-screen-config-options.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

-- now the working widgets
simulator.sleep(10) -- wait 
simulator.setAnalog(1, 50)
simulator.sleep(10) -- wait 
simulator.setAnalog(1, 40)
simulator.sleep(10) -- wait 
simulator.setAnalog(1, 30)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-value-telemetry.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-timer-log.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-timer-log-menu.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-lipo.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-channels.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-line-chart.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-line-chart-options.png")
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/display-widget-text.png")
-- create new model for default home screen
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(20)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.pressKey(KEY_PAGE)
simulator.touch(742, 454)
--simulator.touch(743, 453)
simulator.sleep(2) -- wait 
simulator.screenshot("../assets/display-main-view.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/display-widget-config-options.png")
simulator.pressKey(KEY_RTN,1)
-- get glider mixes library screenshot
simulator.pressKey(KEY_MDL)
simulator.turnRotaryEncoder(4)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/model-mixes-library-glider.png")
simulator.pressKey(KEY_RTN, 1)
